name: Just test

on:
  push:
    branches:
    - master

jobs:
  my-job-name:
     name: Test
     runs-on: self-hosted
     container:
       options: -v /home/oleg/factory/:/drive
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: My first step
         uses: ./.github/actions/my-action
