name: Just test

on:
  push:
   branches:
   - master

# on:
#   schedule:
#     - cron: '20 */1 * * *'

jobs:
  my-job-name:
     name: A new job
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: whoami
         run: whoami
       - name: lookaround
         run: ls -la
       - name: my-action
         run: .github/docs/update.sh {{ secrets.GITHUB_TOKEN }}
