name: Just test

on:
  push:
    branches:
    - master

jobs:
  my-job-name:
     name: Test
     runs-on: self-hosted
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: bare-run
         run: |
             cat > Dockerfile << EOF
             FROM ubuntu:xenial

             RUN echo "aaaa" > product
             RUN ls
             EOF
             docker image build . -t mytest
             docker run --rm -v `pwd`:/drive mytest cp /product /drive
       - name: My first step
         uses: ./.github/actions/my-action
