name: Just test

on:
  push:
    branches:
    - master

jobs:
  my-job-name:
     name: A new job
     runs-on: self-hosted
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: my-action
         uses: actions/my-action
         with:
           mysecret: ${{ secrets.MY_SUPER_SECRET }}
