name: Just test

on:
  push:
   branches:
   - master

# on:
#   schedule:
#     - cron: '20 */1 * * *'

jobs:
  my-job-name:
     name: A new job
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: update
         run: |
           docker image build .github/docs -t docs
           docker run --rm -v `pwd`:/drive docs
           docker image rm docs
       - name: lookaround
         run: ls -l
       - name: push
         run: .github/docs/push.sh {{ secrets.GITHUB_TOKEN }}
