name: Just test

on:
  push:
    branches:
    - master

jobs:
  my-job-name:
     name: Test
     runs-on: self-hosted
     steps:
       - name: bare-run
         run: |
             cat > Dockerfile << EOF
             FROM ubuntu:xenial

             COPY main.c /main.c

             RUN apt-get update -y && \
             apt-get install -y gcc make

             RUN make main && ./main
             RUN ./main && echo $? && ls
             EOF
             docker image build . -t mytest
             docker run --rm -v `pwd`:/drive mytest cp /product /drive
       - name: Checkout
         uses: actions/checkout@v2
       - name: My first step
         uses: ./.github/actions/my-action
