name: Just test

on:
  push:
    branches:
    - master

jobs:
  my-job-name:
     name: Test
     runs-on: self-hosted
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: My first step
         uses: ./.github/actions/my-action
       - name: Upload results
         uses: actions/upload-artifact@v1
         with:
           name: no-matter
           path: product
